version: '3'
services:
  opa:
    image: openpolicyagent/opa:latest
    ports:
      - "8181:8181"
    command:
      - "run"
      - "--server"
      - "--set=decision_logs.console=true"
      - "--log-format=json-pretty"
      - "/rules.rego"
    volumes:
      - ./opa/rules/rules.rego:/rules.rego

  api_server:
    image: jdemo-restful-api:0.0.2
    ports:
      - "8080:8080"
    environment:
      - OPA_ADDR=http://opa:8181
      - POLICY_PATH=/v1/data/rules/main
