opa:
  url: ${OPA_ADDR:http://localhost:8181}
  mainPath: ${MAIN_PATH:/v1/data/rules/main}
  filterPath: ${FILTER_PATH:/v1/data/rules/filter}
  tokenPath: ${FILTER_PATH:/v1/data/rules/token}

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:jwtio-key.pub
